volumes:
  shared-workspace:
      name: "spark-volumes"
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '/home/rjac/workspace/kafka-spark-setup/spark-cluster/workspace'

services:

  master:
    image: rjacdevops/spark-master
    container_name: spark-container
    environment:
      - SPARK_MASTER_HOST=spark-container
    ports:
    - 8080:8080
    - 7077:7077
    volumes:
        - shared-workspace:/opt/workspace

  worker:
      image: rjacdevops/spark-worker
      environment:
          - SPARK_WORKER_CORES=1
          - SPARK_WORKER_MEMORY=2548MB
          - SPARK_MASTER_HOST=spark-container
      ports:
          - "9081-9899:8081"
      volumes:
          - shared-workspace:/opt/workspace
      depends_on:
          - master